export const GET_ENDPOINT = 'GET_ENDPOINT'

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'

export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'

export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const FETCH_SINGLE_REQUEST = 'FETCH_SINGLE_REQUEST'

export const FETCH_SINGLE_SUCCESS = 'FETCH_SINGLE_SUCCESS'

export const FETCH_SINGLE_FAILURE = 'FETCH_SINGLE_FAILURE'

export const posts = 'posts'

export const single = 'single'
